<?php

namespace App\Console\Commands;

use App\Mail\Email;
use App\Models\User;
use App\Models\AssetUser;
use App\Models\JobHistory;
use App\Models\Resignation;
use App\Models\VehicleUser;
use App\Models\AssetHistory;
use App\Models\SalaryHistory;
use App\Models\DepartmentUser;
use Illuminate\Console\Command;
use App\Models\AssetUserHistory;
use App\Models\WorkingShiftUser;
use App\Models\UserEmploymentStatus;
use Illuminate\Support\Facades\Mail;

class SendNoticePeriodEndNotifications extends Command
{
    protected $signature = 'notice:end';
    protected $description = 'Send notice period end notifications to employees';

    public function __construct()
    {
        parent::__construct();
    }

    public function handle()
    {
        $today_last_date_employees = Resignation::whereNotNull('last_working_date')
            ->whereDate('last_working_date', now())
            ->get();

        foreach($today_last_date_employees as $today_last_employee){
            //employee
            $emp_last_date = User::where('id', $today_last_employee->employee_id)->first();

            //close job employment status
            $user_emp_status = UserEmploymentStatus::orderby('id', 'desc')->where('user_id', $emp_last_date->id)->first();
            $user_emp_status->employment_status_id = $today_last_employee->employment_status_id;
            $user_emp_status->end_date = $today_last_employee->last_working_date;
            $user_emp_status->save();

            //close job history
            $job_history = JobHistory::orderby('id', 'desc')->where('user_id', $emp_last_date->id)->first();
            $job_history->end_date = $today_last_employee->last_working_date;
            $job_history->save();

            //close salary history
            $salary_history = SalaryHistory::orderby('id', 'desc')->where('user_id', $emp_last_date->id)->first();
            $salary_history->end_date = $today_last_employee->last_working_date;
            $salary_history->save();

            //close DepartmentUser
            $user_dept = DepartmentUser::orderby('id', 'desc')->where('user_id', $emp_last_date->id)->first();
            $user_dept->end_date = $today_last_employee->last_working_date;
            $user_dept->save();

            //close DepartmentUser
            $user_dept = WorkingShiftUser::orderby('id', 'desc')->where('user_id', $emp_last_date->id)->first();
            $user_dept->end_date = $today_last_employee->last_working_date;
            $user_dept->save();

            //close VehicleUser
            $vehicle_user = VehicleUser::orderby('id', 'desc')->where('user_id', $emp_last_date->id)->where('end_date', NULL)->first();
            if(!empty($vehicle_user)){
                $vehicle_user->end_date = $today_last_employee->last_working_date;
                $vehicle_user->save();
            }

            //close VehicleUser After clearness
            $vehicle_user = VehicleUser::orderby('id', 'desc')->where('user_id', $emp_last_date->id)->where('end_date', NULL)->first();
            if(!empty($vehicle_user)){
                $vehicle_user->end_date = $today_last_employee->last_working_date;
                $vehicle_user->save();
            }

            $userAssets = AssetUser::orderBy('id', 'desc')
                ->where('user_id', $emp_last_date->id)
                ->where('end_date', NULL)
                ->get();

            if (!$userAssets->isEmpty()) {
                foreach ($userAssets as $userAsset) {
                    $userAsset->status = 0; // De-activate assigned asset
                    $userAsset->unassigned_at = $today_last_employee->last_working_date;
                    $userAsset->end_date = $today_last_employee->last_working_date;
                    $userAsset->save();

                    $assetHis = AssetHistory::create([
                        'asset_id' => $userAssets->asset->asset->id,
                        'quantity' => 1,
                        'type' => 1, //induct
                        'remarks' => 'Quantity Increased',
                    ]);

                    if($assetHis){
                        AssetUserHistory::create([
                            'asset_user_id' => $emp_last_date->id,
                            'asset_detail_id' => $userAssets->asset_detail_id,
                            'employee_id' => $emp_last_date->id,
                            'date' => $today_last_employee->last_working_date,
                            'remarks' => 'Auto generated by system.',
                            'type' => 2,
                        ]);
                    }
                }
            }
            //close VehicleUser After clearness

            //de-active employee and remove from employment
            $emp_last_date->status = 0; //set to deactive
            $emp_last_date->is_employee = 0; //set to deactive
            $emp_last_date->save();
        }

        $tomorrow = now()->addDay();
        $employees = Resignation::whereNotNull('last_working_date')
            ->whereDate('last_working_date', $tomorrow)
            ->get();

        $admin_user = User::role('Admin')->first();
        foreach ($employees as $employee) {
            $model = User::where('id', $employee->employee_id)->first();

            $mailData = [
                        'from' => 'termination',
                        'title' => 'Employee Termination Notification',
                        'employee' => $model->first_name.' '.$model->last_name,
                    ];

            //Email Shooting
            if(!empty(sendEmailTo($model, 'employee_termination')) && !empty(sendEmailTo($model, 'employee_termination')['cc_emails'])){
                $to_emails = sendEmailTo($model, 'employee_termination')['to_emails'];
                $cc_emails = sendEmailTo($model, 'employee_termination')['cc_emails'];
                Mail::to($to_emails)->cc($cc_emails)->send(new Email($mailData));
            }else{
                $to_emails = sendEmailTo($model, 'employee_termination')['to_emails'];
                Mail::to($to_emails)->send(new Email($mailData));
            }
            //Email Shooting
        }
    }
}
