<?php
return [
    "employee_salary_details-list",
    "employee_leave_requests-list",
    "employee_leave_requests-create",
    "employee_leave_requests-edit",
    "employee_leave_requests-delete",
    "employee_leave_report-list",
    "employee_attendance_daily_log-list",
    "employee_discrepancies-list",
    "employee_summary-list",
    "bank_accounts-create",
    "bank_accounts-edit",
    "employee_letters-list",
    "notifications-list",
    "tickets-list",
    "tickets-create",
    "tickets-edit",
    "tickets-delete",
    "insurances-create",
    "insurances-edit"
];
